// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oiwzdtujpromfbqlztib.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9pd3pkdHVqcHJvbWZicWx6dGliIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjgzNTIyMzUsImV4cCI6MjA4MzkyODIzNX0.khkpmL5B9NAYsOJ-jx5gx83HFMrwUgrhYEa81f1BoFE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});